### ISSUE TITLE
String should be array

### ISSUE THREAD

**Issue by mgillespie62** [tagyoureit/tableau-identitystore-config-tool#1]
Two values in the JSON doc currently return string values; they should return arrays.
groupClassNames returns "" when empty; should return []
userClassNames returns "" when empty; should return []

When importing the doc into Tableau Server, those fields throw errors.

**Comment by tagyoureit** [comment]
The JSON is currently returning arrays with empty strings... eg
```
"groupClassNames": [ ""]
```
It sounds like you are seeing something different?  Does this format work?

**Comment by mgillespie62** [comment]
Yeah, when we used it at a customer site 2 weeks ago, it did NOT include the square brackets.  Just the double quotes.

Michael Gillespie

t: 206.410.1521
c: 651.329.9638
e: mgillespie@tableau.com<mailto:mgillespie@tableau.com>

**Comment by tagyoureit** [comment]
Yup, it was updated last week.  If you have any other issues please let me know.  Thanks for opening this issue.

**Comment by mgillespie62** [comment]
Well, that figures!  Thanks.

Michael Gillespie

t: 206.410.1521
c: 651.329.9638
e: mgillespie@tableau.com<mailto:mgillespie@tableau.com>
