### ISSUE TITLE
Range Retrieval should be a boolean but defaults to 1500

### ISSUE THREAD

**Issue by SunshineGrrrl** [tagyoureit/tableau-identitystore-config-tool#2]
When using the config tool, on Miscellaneous Settings page, the Range Retrieval variable is set to 1500 instead of the default of false. Attaching a pic of the default as well as a pic of the Tableau help page that explains this particular variable here: https://help.tableau.com/current/server/en-us/ldap_config.htm

![image_720](https://github.com/tagyoureit/tableau-identitystore-config-tool/assets/41353175/8fe21a2d-aebf-480d-b44f-b604a6c4f719)

![image_720](https://github.com/tagyoureit/tableau-identitystore-config-tool/assets/41353175/05e93767-f987-4bb3-b677-51ce607fe480)

**Comment by tagyoureit** [comment]
Updated.  Ty!
